-- AlterTable
ALTER TABLE "Contrato" ALTER COLUMN "valor" SET DATA TYPE DECIMAL(18,2),
ALTER COLUMN "mediaMensal" SET DATA TYPE DECIMAL(18,2),
ALTER COLUMN "total" SET DATA TYPE DECIMAL(18,2);

-- AlterTable
ALTER TABLE "Parcela" ALTER COLUMN "valor" SET DATA TYPE DECIMAL(18,2);
